#!/bin/bash

# Alternative method: Extract certificate directly from Keychain
# This might work better than using a .p12 file

echo "🔍 Alternative Method: Extract from Keychain"
echo ""
echo "Sometimes it's better to extract directly from Keychain."
echo ""
echo "1. Open Keychain Access"
echo "2. Search for: 'Pass Type ID: pass.com.thequestsapp.questcard'"
echo "3. Right-click on the certificate → 'Get Info'"
echo "4. Check that it shows 'Private Key' with a disclosure triangle"
echo ""
echo "If the certificate doesn't show a private key, it wasn't exported correctly."
echo ""
echo "To fix this, you need to export BOTH the certificate AND the key:"
echo ""
echo "1. In Keychain Access, select the CERTIFICATE (not the key)"
echo "2. Right-click → Export"
echo "3. File Format: 'Personal Information Exchange (.p12)'"
echo "4. Make sure the password dialog shows 'Include Extended Attributes'"
echo "5. UNCHECK 'Include Extended Attributes' if it's checked"
echo "6. Set password"
echo ""
echo "If that doesn't work, try this method:"
echo ""
echo "Method 2: Export from Keychain using security command"
echo "-----------------------------------------------------"
echo ""
echo "Run this command (it will ask for your Mac password):"
echo ""
echo "security find-identity -v -p codesigning | grep 'Pass Type ID'"
echo ""
echo "This will show if the certificate is accessible in Keychain."
echo ""
echo "Then try:"
echo "security find-certificate -a -c 'Pass Type ID: pass.com.thequestsapp.questcard' -p | openssl x509 -text"
